version: '3.3'
volumes: 
  db-data:
services:
  nginx_php:
    container_name: docker-nginx-php
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www/php_docker
      - ./docker/nginx/default-php.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  node:
    container_name: docker-node
    build:
      context: ./docker/node
    working_dir: /usr/src/app
    command: npm start
    volumes:
      - ./front:/usr/src/app
    ports:
      - 3000:3000
  php:
    container_name: docker-php
    build:
      context: ./docker/php
    working_dir: /usr/src/php_docker
    volumes:
      - ./api:/var/www/php_docker
      - ~/.bash_history:/root/.bash_history
    ports:
      - 9000:9000
    restart: on-failure
  database:
    image: mysql:8.0
    container_name: docker-database
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: docker-adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8888:8080